//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.21 at 03:37:18 PM CEST 
//

package gcmserver.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Devices }
	 * 
	 */
	public Devices createDevices() {
		return new Devices();
	}

	/**
	 * Create an instance of {@link Devices.Device }
	 * 
	 */
	public Devices.Device createDevicesDevice() {
		return new Devices.Device();
	}

	/**
	 * Create an instance of {@link Topics }
	 * 
	 */
	public Topics createTopics() {
		return new Topics();
	}

	/**
	 * Create an instance of {@link Topics.Topic }
	 * 
	 */
	public Topics.Topic createTopicsTopic() {
		return new Topics.Topic();
	}
}
